### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by dragoon25** [strmark/piclodio4#27]
Hello

i have some error on installation back and frontend on Raspbian BullEye 11 with pi3b+

![2024-07-29_134019](https://github.com/user-attachments/assets/78bfedc4-08d7-4ffd-914a-29c8dede02cd)

it is a new install from raspbian iso , have you a tutorial updated ? 

Thanks

**Comment by strmark** [comment]
Hi, I frequently update the project, but I forgot to do the same for the README files, the project works now with java 17 and node 18. So I have updated the README files. I still have to do the installation myself on a pi3b again to check if it works.

**Comment by dragoon25** [comment]
Yes i installed the openjdk-17-jdk and nodejs 18x 

Thanks if you update the installation guide.

**Comment by dragoon25** [comment]
![2024-07-30_085225](https://github.com/user-attachments/assets/4f37ad24-3864-47a2-9a85-4744d0325315)

**Comment by strmark** [comment]
You cloned the repository. Inside that repository there is the folder "back" and below that there is a folder "database", inside that folder you will find the piclodio.db.... file. In the folder back/src/main/resources you will find the application.yml which contains the reference to this database.

**Comment by dragoon25** [comment]
ok i understand , so if i cloned the project , i stay to home/pi and not directly on /piclodio4/back
so the command working after go to the correct folder 
![2024-07-30_143219](https://github.com/user-attachments/assets/595bc287-a1b6-4d12-9101-91e7f346f095)

**Comment by dragoon25** [comment]
the same for the mvn install if i stay to the folder /piclodio4/back
![2024-07-30_144534](https://github.com/user-attachments/assets/aae9eb43-47c3-4883-a430-4b1f2dfd7213)

**Comment by strmark** [comment]
The database is copied to /home/pi/database the java jar is copied after packaging to /home/pi/piclodio. The start database is inside piclodio/back/database and is copied to /home/pi/database so when the jar is run, it will find the database inside /home/pi/database. After that you could create a service which starts the jar.

When you do the testing in piclodio/back with mvn spring-boot:run it will also find the database since that folder is inside back/ then you can go to localhost:8000 and see a swagger ui interface being opened so you can test the interface.

**Comment by strmark** [comment]
the mvn install is inside piclodio4/back since the pom.xml for maven is iniside that folder, same for the mvn spring-boot:run since the pom.xml is inside the back folder.

**Comment by dragoon25** [comment]
ok so the backend works now 
![2024-07-30_160736](https://github.com/user-attachments/assets/42d5df29-17c6-406e-8615-2c77c7127447)

**Comment by dragoon25** [comment]
i blocked for the fronted on 'npm install8'  
![2024-07-30_161920](https://github.com/user-attachments/assets/ef233052-eee4-4964-99c3-b79dbbaaf986)

**Comment by strmark** [comment]
It should be npm install.

**Comment by strmark** [comment]
The "npm install -g @angular/cli" will install the angular client so you can use the ng command.

**Comment by dragoon25** [comment]
i check this later , i have an error out memory 
![2024-07-30_173337](https://github.com/user-attachments/assets/dbd54369-800b-4a93-9c08-1d52aacb87cb)
and
![2024-07-30_173709](https://github.com/user-attachments/assets/f5cf3e12-bb2b-4bee-9747-fa943bc292df)

**Comment by strmark** [comment]
You don't have to sudo those command's. So npm install and ng serve ---host 0.0.0.0

**Comment by dragoon25** [comment]
i reboot he pi3 and have the same error : 
_### FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory_

i test this : `export NODE_OPTIONS="--max-old-space-size=1024"` before do the `npm install` but not working too.

**Comment by strmark** [comment]
I will have to check it on a Pi3B, I will get back to you on that.

**Comment by strmark** [comment]
I added the package-lock.json to the repository again. I had to set the node_options. 
export NODE_OPTIONS="--max-old-space-size=1024"
Then I could do the "npm install". The "ng serve" takes a lot of resources and testing the front-end is then hard. So I went and compiled the pages with "ng build --configuration production --aot" and copied it to the location of nginx.

**Comment by dragoon25** [comment]
So what can i do , clone again the project from github ?   can you tell me the new steps ?

**Comment by strmark** [comment]
You could do a "git pull" inside the piclodio4 folder and follow the instructions of the README.md in de frontend folder. If that doesn't work you could clone the folder again.

**Comment by dragoon25** [comment]
npm don't work if i git pull but works with the git clone again .
![2024-08-02_110138](https://github.com/user-attachments/assets/b110762f-6adc-4c81-9b7a-c2fbc17b701b)

ng build do a heap out memory but i maybe do a wrong thing. 
![2024-08-02_112119](https://github.com/user-attachments/assets/a493b5b6-9d19-4adf-849a-63810fd8a9a3)
or by dint of doing manipulations it messes up, I rebooted it but nothing works.

**Comment by dragoon25** [comment]
if i do `export NODE_OPTIONS="--max-old-space-size=1024"`  before the `ng build`  it passed : 
![2024-08-02_114234](https://github.com/user-attachments/assets/a96ef2a1-6742-41b0-b945-938a8913853f)

**Comment by dragoon25** [comment]
i have the frontend view : 
![2024-08-02_120743](https://github.com/user-attachments/assets/028a6023-3da3-41b3-a671-cb10a8679088)

but the backend don't automatic, i will check this part , works manually with `mvn spring-boot:run` but not automatic after reboot.

**Comment by strmark** [comment]
You could run the jar inside /home/pi/piclodio. So change to the folder /home/pi/piclodio and run the jar:
"/usr/bin/java -jar piclodio-0.0.1-SNAPSHOT.jar" if it works fine then the I would give the same logging as running with maven. If something is wrong it will give you errors. 

Also you can check with: "sudo systemctl status piclodio" to see if the service is running fine.

**Comment by dragoon25** [comment]
![2024-08-02_133723](https://github.com/user-attachments/assets/dc9c94aa-e053-44fe-820b-a4f375b0a929)
The service is running but backend have no access at ip:8000 on automatic, just manually if i do `mvn spring-boot:run`

**Comment by strmark** [comment]
If you stop the service "sudo systemctl stop piclodio" can you run the jar from within the folder /home/pi/picliodio with the command "/usr/bin/java -jar piclodio-0.0.1-SNAPSHOT.jar"

**Comment by dragoon25** [comment]
yes i can run java if i stop but i have an error 3091 
![2024-08-02_150443](https://github.com/user-attachments/assets/6b3a546a-f7c2-4c0d-839c-c9200abaa19b)

**Comment by dragoon25** [comment]
i find with debug , it can't find the database.  i do again the `cp database/piclodio.db.* /home/pi/piclodio/database/`
maybe the error due to the git clone again this morning.

**Comment by dragoon25** [comment]
i already have an other error when i start a radio : 
![2024-08-02_151938](https://github.com/user-attachments/assets/55c3885b-1d1a-4c2b-9e87-0deb8d2801a6)
Maybe do a new installation with a fresh sd raspbian install for do again a full install with new tutorial :-)

**Comment by strmark** [comment]
Looks like the database is out of sync.  Clicking the Stop button twice will stop the cvlc jobs. When selecting some station from the Internet Radio page and clicking to play from there will fill the Webradio. and setting that station to the new default.

Another tip:
The program uses cvlc the command line version of VLC. 
You can tweak settings for cVLC inide VLC. So if you start VLC and stream an Url, so you can see if cVLC uses the correct settings. For instance the set HDMI for sound output, or the headphone port for output.

**Comment by strmark** [comment]
Closed, since no more questions about the installation are asked.
